// File generated by FlutterFire CLI.
// This is a placeholder file. You need to run:
// flutterfire configure
// to generate the actual firebase_options.dart file with your project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Run `flutterfire configure` to generate this file with your actual
/// Firebase project configuration.
///
/// Example:
///```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Run: flutterfire configure

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJK894vzNoJaGbXRwhutV7rZdrLI2M0CI',
    appId: '1:156660024726:web:0903224938a571466589b7',
    messagingSenderId: '156660024726',
    projectId: 'auraap-f38f5',
    authDomain: 'auraap-f38f5.firebaseapp.com',
    storageBucket: 'auraap-f38f5.firebasestorage.app',
    measurementId: 'G-LBN6969T6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoXIArZQjinQlZTewYHEy9S7ZD_MJVBLE',
    appId: '1:156660024726:android:1653dce4263f9e626589b7',
    messagingSenderId: '156660024726',
    projectId: 'auraap-f38f5',
    storageBucket: 'auraap-f38f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRcDUs7KLycgx26F-T498cfklZ6sfLW7I',
    appId: '1:156660024726:ios:040605cf6e796f5e6589b7',
    messagingSenderId: '156660024726',
    projectId: 'auraap-f38f5',
    storageBucket: 'auraap-f38f5.firebasestorage.app',
    iosClientId: '156660024726-ft3qplec75h3fn21vu5fqelldpmkr6mk.apps.googleusercontent.com',
    iosBundleId: 'au',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRcDUs7KLycgx26F-T498cfklZ6sfLW7I',
    appId: '1:156660024726:ios:8318ed98b4c762f86589b7',
    messagingSenderId: '156660024726',
    projectId: 'auraap-f38f5',
    storageBucket: 'auraap-f38f5.firebasestorage.app',
    iosClientId: '156660024726-gijseuitd6ld7uka7f2g42thdv70e60o.apps.googleusercontent.com',
    iosBundleId: 'auraapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJK894vzNoJaGbXRwhutV7rZdrLI2M0CI',
    appId: '1:156660024726:web:b63a8c28409c24996589b7',
    messagingSenderId: '156660024726',
    projectId: 'auraap-f38f5',
    authDomain: 'auraap-f38f5.firebaseapp.com',
    storageBucket: 'auraap-f38f5.firebasestorage.app',
    measurementId: 'G-CJMV3BZ10N',
  );

}